FROM nvidia/cuda:12.4.1-devel-ubuntu22.04
LABEL authors="Jordan Lam jordlam@mit.edu, Keawe Mann keawem@mit.edu"

ARG DEBIAN_FRONTEND=noninteractive

# Install needed packages.
RUN apt-get update
RUN apt update
RUN apt -y install python3
