#!/bin/bash

# ----------------------------------------------------------------------------------
# ------------------------ PUT YOUR RUNNING COMMAND(s) HERE ------------------------
# ----------------------------------------------------------------------------------
# ----- This sctipt is executed inside our GPU environment:
# -----     * all output files generated by `build.sh` are placed in this script's workdir
# -----     * feel free to execute `ls` form here to check the content of the workdir
# ----------------------------------------------------------------------------------

# We can see what's on the execution server in the home dir:
echo "Content:"; ls

# Run tests.
# echo -e "JAX tests...\n"
# python3 jax_test.py
# echo -e "torch tests...\n"
# python3 torch_test.py
# echo -e "\n"
# python3 arch_test.py
echo -e "\nCUDA tests..."
./vector_add

# Run other files
echo -e "Running obj loaders...\n"
./obj_loader
echo -e "Running camera, light loaders...\n"
./fbx_loader
